name: raft
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - MultiParamTypeClasses
  - PolyKinds
  - RankNTypes
  - TypeOperators
  - UnicodeSyntax

dependencies:
  - base
  - microlens
  - microlens-th

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - raft
      - hspec
